name: Build for Windows XP & Server 2003

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MXE for Windows XP (i686-static)
        uses: mxe/setup-mxe@v1
        with:
          mxe-target: i686-w64-mingw32.static
          packages: openssl

      - name: Compile Windows XP Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 main.cpp -o keygen_xp.exe
          echo "Successfully compiled keygen_xp.exe"

      - name: Compile Windows Server 2003 Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 Srv2003KGmain.cpp -o Srv2003KG.exe
          echo "Successfully compiled Srv2003KG.exe"

      - name: Upload Executables as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: |
            keygen_xp.exe
            Srv2003KG.exe
