name: Build for Windows XP & Server 2003

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: mxe
          key: ${{ runner.os }}-mxe

      - name: Install MXE dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            autopoint \
            bash \
            bison \
            bzip2 \
            flex \
            g++ \
            g++-multilib \
            gettext \
            git \
            gperf \
            intltool \
            libc6-dev-i386 \
            libclang-dev \
            libgdk-pixbuf2.0-dev \
            libltdl-dev \
            libgl-dev \
            libpcre2-dev \
            libssl-dev \
            libtool-bin \
            libxml-parser-perl \
            lzip \
            make \
            openssl \
            p7zip-full \
            patch \
            perl \
            python3 \
            python3-mako \
            python3-packaging \
            python3-pkg-resources \
            python3-setuptools \
            python-is-python3 \
            ruby \
            sed \
            sqlite3 \
            unzip \
            wget \
            xz-utils

      - name: Install MXE
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/mxe/mxe.git
          cd mxe
          make MXE_TARGETS='i686-w64-mingw32.static' openssl
        shell: bash

      - name: Add MXE to PATH
        run: echo "$(pwd)/mxe/usr/bin" >> $GITHUB_PATH

      - name: Compile Windows XP Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 main.cpp -o keygen_xp.exe -lssl -lcrypto -lws2_32 -lcrypt32 -lz -lgdi32
          echo "Successfully compiled keygen_xp.exe"

      - name: Compile Windows Server 2003 Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 Srv2003KGmain.cpp -o Srv2003KG.exe -lssl -lcrypto -lws2_32 -lcrypt32 -lz -lgdi32
          echo "Successfully compiled Srv2003KG.exe"

      - name: Upload Executables as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: |
            keygen_xp.exe
            Srv2003KG.exe
