name: Build for Windows XP & Server 2003

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MXE
        run: |
          sudo apt-get update
          sudo apt-get install -y wget make gcc g++ pkg-config
          git clone https://github.com/mxe/mxe.git
          cd mxe
          make MXE_TARGETS='i686-w64-mingw32.static' openssl
        shell: bash

      - name: Add MXE to PATH
        run: echo "$(pwd)/mxe/usr/bin" >> $GITHUB_PATH

      - name: Compile Windows XP Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 main.cpp -o keygen_xp.exe
          echo "Successfully compiled keygen_xp.exe"

      - name: Compile Windows Server 2003 Keygen
        run: |
          i686-w64-mingw32.static-g++ -Wall -Wextra -g3 Srv2003KGmain.cpp -o Srv2003KG.exe
          echo "Successfully compiled Srv2003KG.exe"

      - name: Upload Executables as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: |
            keygen_xp.exe
            Srv2003KG.exe
